### ISSUE TITLE
Playlist Music  is not properly pausing/unpausing

### ISSUE THREAD

**Issue by Shakespar** [Matthew-Whitlock/FoundryVTT-music-permissions#4]
Something in the module is causing music to play again at the start instead of resuming.  disabling the module made it work again.

**Comment by Matthew-Whitlock** [comment]
Hello,

This issue is with the experimental local-playback features - it's still very much a WIP, particularly the UI controls for it. For now, please go to the module settings and set "Minimum local-playback permissions" to "Disabled".

I'll make it more clear soon that the feature is experimental and that disabled is the recommended setting. Let me know if changing that doesn't solve the problem for you, though!
